FROM python:3.10-slim

WORKDIR /usr/src/app

RUN apt update
RUN apt install curl -y
RUN apt install iputils-ping -y

COPY requirements.txt ./
RUN pip install --no-cache-dir --no-deps -r requirements.txt
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

COPY . .
ARG EXPOSED_PORT
EXPOSE ${EXPOSED_PORT}
ENV PERSISTENT_DATA="/data"
ENV INDEX_CONFIG_PATH="/data/config/indexes.json"
ENV RETRIEVER_ENDPOINT="http://127.0.0.1:${EXPOSED_PORT}" 

CMD ["bash", "run_retriever.sh"]
