services:

  gradio:
    build: 
      context: .
    pull_policy: build
    restart: unless-stopped
    network_mode: host
    environment:
      - OPENAI_API_ENDPOINT_URL=${OPENAI_API_ENDPOINT_URL}
      - ROOT_PATH=/dev
    volumes:
      - ./playground-data:/data:rw
